# Generated by Django 3.2.11 on 2022-01-16 20:33

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.CharField(default=api.models.random_id_unique, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('players', models.ManyToManyField(related_name='game', to='api.GamePlayer')),
            ],
        ),
    ]
