name: build

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
   -  name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: mycowgame.com/frontend:latest
        file: docker/Dockerfile.prod
