FROM node:14-slim as builder

WORKDIR /app
COPY ./app/package.json ./
RUN yarn install

ARG REACT_APP_API_SERVER
ENV REACT_APP_API_SERVER $REACT_APP_API_SERVER
ENV GENERATE_SOURCEMAP=false
COPY ./app ./
RUN yarn build

FROM nginx:alpine
COPY docker/default.conf.template /etc/nginx/templates/
COPY --from=builder /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
