name: 'deploy'

input:
  tag:
  config:

permissions:
  packages: write

runs:
  using: "composite"
  steps:
  - name: apply
    uses: actions-hub/kubectl@master
    env:
      KUBE_CONFIG: ${{ inputs.config }}
    with:
      args: apply -k ./${{ inputs.tag }}/deployment
