FROM python:3.7-buster

WORKDIR /code

RUN pip install pylint

COPY ./requirements.txt ./

RUN pip install -r requirements.txt

RUN pip install autopep8 pytest pytest-django pylint-django

ENV PYTHONPATH /code

ENV DJANGO_SETTINGS_MODULE=app.settings.development