FROM python:3.7-buster

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY ./ /code/
WORKDIR /code

# RUN pip install pylint autopep8 pytest pytest-django pylint-django

# ENV PYTHONPATH /app

ENV DJANGO_SETTINGS_MODULE=app.settings.development 
CMD python manage.py migrate && python manage.py runserver 0.0.0.0:8000
