namespace: mycowgame-com-frontend-testing

bases:
  - ../../base

configMapGenerator:
- name: mycowgame-com-frontend
  env: config.properties

resources:
  - namespace.yml

images:
- name: registry.gitlab.com/jnewb-bclaw/mycowgame.com/frontend
  newName: registry.gitlab.com/jnewb-bclaw/mycowgame.com/frontend/develop

patches:
  - target:
      kind: Ingress
      name: mycowgame-com-frontend
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: testing.mycowgame.com
      - op: replace
        path: /spec/tls/0/hosts/0
        value: testing.mycowgame.com