name: build

on:
  push:
    branches:
      - 'master'

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - name: setup docker buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver: docker
    - name: build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ghcr.io/jnewb1/mycowgame.com/frontend:latest
        file: docker/Dockerfile.prod
        context: "{{defaultContext}}:frontend"

  build-backend:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - name: setup docker buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver: docker
    - name: build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ghcr.io/jnewb1/mycowgame.com/backend:latest
        file: docker/Dockerfile.prod
        context: "{{defaultContext}}:backend"
