name: deploy

on:
  push:
    branches:
      - 'master'

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: kubeconfig
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
      - name: deploy
        run: kubectl apply -f $GITHUB_WORKSPACE/frontend/deployment/deployment.yml
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: kubeconfig
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
      - name: deploy
        run: kubectl apply -f $GITHUB_WORKSPACE/backend/deployment/deployment.yml
